[meta]
name = "Ultimate Medals++"
author = "Catalistique"
category = "Race"
version = "0.0.1"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "WarriorMedals" ]